### ISSUE TITLE
Registration improvement

### ISSUE THREAD

**Issue by krahamath** [mage2/laravel-ecommerce#120]
I see registration, it should say once click the register button. Your account created and click here to login that takes to the login page to login and after login my account should say verify your email like notification alert.

**Comment by krahamath** [comment]
Please consider this

**Comment by indpurvesh** [comment]
@krahamath User Activation required only if you set to Yes in Admin Configuration (Default is no.)

I will keep this issue open because once i will finished resent activation mail Route is done then i will close this issue.

<img width="1065" alt="screen shot 2018-02-25 at 1 15 55 pm" src="https://user-images.githubusercontent.com/4218702/36636561-145ce05e-1a2e-11e8-8e8a-669fdfd5a44b.png">

**Comment by indpurvesh** [comment]
@krahamath Resend Activation Email link Mail is done.

Fixed to checked.

**Comment by krahamath** [comment]
Thank you
