### ISSUE TITLE
Products not displaying frontend ...

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [mage2/laravel-ecommerce#57]
Previously products was displaying as dummy data as i install this package but there images was not displaying so i deleted all dummy data products and added new 5 products but no product is displaying in frontend.
Error message 👍 
Sorry No Feature Product.

**Comment by indpurvesh** [comment]
@ZaheerAbbasAghani 

i just comment out attribute feature few days ago because i was working on it. I did commit yesterday so 

Just run command composer update. 

once you go to product edit page..
click on Attribute tab-> you see a 
drop down field saying is featured?

Just update product it will work

**Comment by ZaheerAbbasAghani** [comment]
After composer update display below error

**Comment by indpurvesh** [comment]
I think you have to re install it from scratch. 

Otherwise you might get error for table does not exist.

**Comment by ZaheerAbbasAghani** [comment]
ok i am installing it again

**Comment by ZaheerAbbasAghani** [comment]
now as i install again i am getting below error

![capture](https://user-images.githubusercontent.com/14222731/28659639-a64e3358-72c9-11e7-82f9-47b95187c5ec.PNG)

**Comment by ZaheerAbbasAghani** [comment]
![capture](https://user-images.githubusercontent.com/14222731/28659813-2893b3e2-72ca-11e7-925a-32a3add2e87a.PNG)

**Comment by indpurvesh** [comment]
fixed.
